version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: wordsto_postgres
    environment:
      POSTGRES_USER: wordsto
      POSTGRES_PASSWORD: wordsto123
      POSTGRES_DB: wordsto_link
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: wordsto_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: wordsto_adminer
    ports:
      - "8000:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
